// /api/stripe-webhook.js
// Handles Stripe webhook events for SurfShield subscriptions.
// On checkout.session.completed: creates the user (if new) + subscription + license.
// On subscription.updated: syncs status to Supabase.
// On subscription.deleted: cancels subscription, deactivates license.

const Stripe = require('stripe');
const { createClient } = require('@supabase/supabase-js');

const stripe = new Stripe(process.env.STRIPE_SECRET_KEY);
const webhookSecret = process.env.STRIPE_WEBHOOK_SECRET;

// Admin Supabase client — uses the service role key (bypasses RLS).
// Required because the webhook isn't a logged-in user; it acts on the
// system's behalf.
const supabase = createClient(
  process.env.SUPABASE_URL,
  process.env.SUPABASE_SECRET_KEY,
  { auth: { autoRefreshToken: false, persistSession: false } }
);

// Stripe sends the request body as raw bytes; we need them intact to
// verify the signature, so bodyParser must be disabled.
async function getRawBody(req) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    req.on('data', chunk => chunks.push(chunk));
    req.on('end', () => resolve(Buffer.concat(chunks)));
    req.on('error', reject);
  });
}

// Look up an auth user by email; return null if not found.
async function findUserByEmail(email) {
  // listUsers paginates 50 at a time. For the early stage of this product
  // this is fine; later we may need a different lookup strategy.
  const { data, error } = await supabase.auth.admin.listUsers({ perPage: 200 });
  if (error) throw error;
  return data.users.find(u => u.email && u.email.toLowerCase() === email.toLowerCase()) || null;
}

// Find or create a Supabase auth user for this email.
async function findOrCreateUser(email) {
  const existing = await findUserByEmail(email);
  if (existing) {
    console.log('[webhook] reusing existing user:', existing.id);
    return existing.id;
  }
  const { data, error } = await supabase.auth.admin.createUser({
    email,
    email_confirm: true // skip email verification — payment is proof of identity
  });
  if (error) throw error;
  console.log('[webhook] created new user:', data.user.id);
  return data.user.id;
}

// Idempotency check — has this subscription already been processed?
async function subscriptionExists(stripeSubscriptionId) {
  const { data, error } = await supabase
    .from('subscriptions')
    .select('id')
    .eq('stripe_subscription_id', stripeSubscriptionId)
    .maybeSingle();
  if (error) throw error;
  return !!data;
}

// ── Event handlers ────────────────────────────────────────────────────
async function handleCheckoutCompleted(session) {
  const email = session.customer_details?.email || session.customer_email;
  if (!email) throw new Error('No email on checkout session');

  const stripeCustomerId     = session.customer;
  const stripeSubscriptionId = session.subscription;

  if (!stripeSubscriptionId) {
    console.log('[webhook] checkout has no subscription id (one-time payment?), skipping');
    return;
  }

  // Idempotency: if Stripe re-sends this event (e.g. on retry after a
  // transient error) we mustn't create duplicate rows.
  if (await subscriptionExists(stripeSubscriptionId)) {
    console.log('[webhook] subscription already processed, skipping:', stripeSubscriptionId);
    return;
  }

  // Pull the subscription's current state (status, period end) from Stripe
  // — checkout.session doesn't include these fields in full detail.
  const subscription = await stripe.subscriptions.retrieve(stripeSubscriptionId);

  const userId = await findOrCreateUser(email);

  // Insert subscription row.
  const { data: subRow, error: subErr } = await supabase
    .from('subscriptions')
    .insert({
      user_id: userId,
      status: subscription.status, // 'active', 'trialing', etc.
      stripe_customer_id: stripeCustomerId,
      stripe_subscription_id: stripeSubscriptionId,
      current_period_end: new Date(subscription.current_period_end * 1000).toISOString()
    })
    .select()
    .single();
  if (subErr) throw subErr;
  console.log('[webhook] subscription row created:', subRow.id);

  // Insert license row. license_key is auto-generated by your trigger.
  const { data: licenseRow, error: licErr } = await supabase
    .from('licenses')
    .insert({
      user_id: userId,
      subscription_id: subRow.id,
      is_active: true
    })
    .select('license_key')
    .single();
  if (licErr) throw licErr;
  console.log('[webhook] license created for user', userId, '→', licenseRow.license_key);

  // (Future: send welcome email via Resend with sign-in link)
}

async function handleSubscriptionUpdated(subscription) {
  const { error } = await supabase
    .from('subscriptions')
    .update({
      status: subscription.status,
      current_period_end: new Date(subscription.current_period_end * 1000).toISOString()
    })
    .eq('stripe_subscription_id', subscription.id);
  if (error) throw error;
  console.log('[webhook] subscription', subscription.id, 'updated to', subscription.status);
}

async function handleSubscriptionDeleted(subscription) {
  // Mark the subscription itself cancelled.
  const { data: subRow, error: subErr } = await supabase
    .from('subscriptions')
    .update({ status: 'cancelled' })
    .eq('stripe_subscription_id', subscription.id)
    .select()
    .single();
  if (subErr) throw subErr;

  // Deactivate any licenses tied to it. Keys remain in the table for
  // audit trail, but is_active=false means /api/detect's gate will
  // reject them.
  const { error: licErr } = await supabase
    .from('licenses')
    .update({ is_active: false })
    .eq('subscription_id', subRow.id);
  if (licErr) throw licErr;

  console.log('[webhook] subscription', subscription.id, 'cancelled, licenses deactivated');
}

// ── Main handler ──────────────────────────────────────────────────────
module.exports = async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  let event;
  try {
    const rawBody = await getRawBody(req);
    const sig = req.headers['stripe-signature'];
    event = stripe.webhooks.constructEvent(rawBody, sig, webhookSecret);
  } catch (err) {
    console.error('[webhook] signature verification failed:', err.message);
    return res.status(400).json({ error: 'Invalid signature' });
  }

  console.log('[webhook] received event:', event.type);

  try {
    switch (event.type) {
      case 'checkout.session.completed':
        await handleCheckoutCompleted(event.data.object);
        break;
      case 'customer.subscription.updated':
        await handleSubscriptionUpdated(event.data.object);
        break;
      case 'customer.subscription.deleted':
        await handleSubscriptionDeleted(event.data.object);
        break;
      default:
        console.log('[webhook] unhandled event type:', event.type);
    }
    return res.status(200).json({ received: true });
  } catch (err) {
    console.error('[webhook] handler error:', err);
    // Return 500 so Stripe retries the delivery.
    return res.status(500).json({ error: err.message });
  }
};

module.exports.config = {
  api: { bodyParser: false }
};
